### ISSUE TITLE
Please update package.json

### ISSUE THREAD

**Issue by phanimahesh** [JakubOnderka/api-blueprint-validator#2]
Currently you declare a hard-coded version dependency on `protagonist`. Can you either update the dependency to the latest (v0.17.1) or switch to an appropriate semver range instead?

**Comment by bdeanindy** [comment]
+1
protagonist version needs to be bumped to support Node.js > 0.11.x versions.

**Comment by bootstraponline** [comment]
+1

api-blueprint-validator is unusable on node 0.12 due to the lock on the old protagonist.

**Comment by JakubOnderka** [comment]
Fixed in 0.1.3 version

**Comment by bootstraponline** [comment]
Thanks!
